language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  matrix:
    - EMACS=emacs
    - EMACS=emacs24
    - EMACS=emacs-snapshot
  global:
    - CASK=$HOME/.cask/bin/cask
    # Turn on --use-mirrors option everywhere (even in tox):
    - PIP_USE_MIRRORS=t
    # Use Python version of the one used for running tox
    - TOXENV=py
matrix:
  allow_failures:
    # Allow failures with EMACS=emacs
    - env: EMACS=emacs
    - env: EMACS=emacs-snapshot
before_install:
  - pip install -q virtualenv tox
  - pip install -q --requirement requirements.txt

  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi

  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - curl -fsSkL
        --max-time 10
        --retry 10
        --retry-delay 10
        https://raw.github.com/cask/cask/master/go | python

  # The following command does (should) not have any effect on test,
  # but to separate installation phase and testing phase:
  - make before-test
script:
  make travis-ci
after_failure:
  - cat elpa/install.log
